### ISSUE TITLE
Project should be split into GSL versions to avoid linker errors

### ISSUE THREAD

**Issue by kraythen** [GuillaumeGomez/rust-GSL#57] opened 2018-06-06 03:54 UTC
Currently if the project is built against the current GSL then it causes linker errors from deprecated functions. This makes the project very hard to use. Can we split it into a version scheme that matches GSL versions? Then make it so that the user should use that version. I would suggest for 1.6 or other GSL versions the code should be branched and then for the current 2.4 it should be branched as well. Then the user can chose the GSL version that fits their system. I would be happy to help.

**Comment by GuillaumeGomez** [comment] 2018-06-06 08:10
I found the current way of splitting versions nice... Just enabling a feature seems simpler to me than playing with versions but not so sure about users...

**Comment by kraythen** [comment] 2018-06-06 17:58
I think it would be better for future versions but features is ok. I committed some documentation fixes for what I needed to do to get to use the crate. That would have saved this newbie a lot of time. However I wish there would be a release 1.0.0 minimum of this because including 0.x dependencies in production code makes managers jumpy. Thats why I thought tieiing it to GSL versions would be good.

**Comment by GuillaumeGomez** [comment] 2018-06-06 21:04
The issue is that GSL doesn't follow semver. So following it in rust would be very problematic or would force us to break semver...

**Comment by kraythen** [comment] 2018-06-07 00:31
Well could we at least do a 1.0? It seems to be baked and i would feel better using a 1.0 in prod.

**Comment by GuillaumeGomez** [comment] 2018-06-07 08:18
Yes, at this point I suppose we can.

**Comment by kraythen** [comment] 2018-06-07 21:55
Great! I think more documentation would be good but this lib is pretty well sorted. We could add some rust based tools into the package but so far seems to work. :)

**Comment by GuillaumeGomez** [comment] 2018-06-08 08:40
I'll close this issue then.

**Closed by GuillaumeGomez** 2018-06-08 08:40 UTC
